### ISSUE TITLE
彈幕無法顯示

### ISSUE THREAD

**Issue by diedbug2002** [Tornaco/ShortX-Release#1]
**Describe the bug（现象描述）**
彈幕無法顯示，且第一次完成Direct Action彈幕設定後，App崩潰
另外建議，移動左上X位置，每次只是要回上一層，就直接把APP關了

**To Reproduce**（如何复现）
無論是Direct Action或Rule皆無法

**Screenshots**（截图）
無

**Version（发现问题的版本）:**
 - OS: A12
 - Version：1.0.0

**Additional context**（其他信息）
無

**Logs**（日志文件）
[ShortX-Log-2023-0613-164518.zip](https://github.com/Tornaco/ShortX-Release/files/11732737/ShortX-Log-2023-0613-164518.zip)

**Comment by Tornaco** [comment]
@diedbug2002  收到，今天推动了新版，可以再试试弹幕。

**Comment by diedbug2002** [comment]
解決了
