### ISSUE TITLE
功能建议：定位设置

### ISSUE THREAD

**Issue by RejectVanity** [Tornaco/ShortX-Release#2]
Play store上的最新版本，触发器支援定位设置，但动作却不支援。
希望开发者大佬在后续版本加上。

（题外话：大佬的软件真好用，很适合我这种对于文本配置情景模式一窍不通的小白）

**Comment by Tornaco** [comment]
@RejectVanity  感谢；后面会增加。

**Comment by Tornaco** [comment]
新版本增加 @RejectVanity
